export type ExplorerThemeId =
  | "sunset-vellum"
  | "gilded-vellum"
  | "sunset-synthwave"
  | "pixel-arcade"
  | "pastel-butterfly"
  | "art-nouveau-fairies"
  | "lunar-ink-observatory"
  | "solarpunk-glasshouse"
  | "bioluminescent-tidepool"
  | "gothic-botanical-lab"
  | "bauhaus-signal-room"
  | "desert-chrome-mirage"
  | "paper-lantern-rain"
  | "arctic-aurora-codex";

export type ThemeNavKey = "atlas" | "gates" | "library" | "flow" | "run" | "compare" | "search";

type ThemeVars = Record<`--${string}`, string>;

export interface ExplorerTheme {
  id: ExplorerThemeId;
  name: string;
  shortName: string;
  description: string;
  art?: string;
  colorScheme: "dark" | "light";
  swatches: string[];
  brandGlyph: string;
  navGlyphs: Record<ThemeNavKey, string>;
  typography: string;
  iconography: string;
  variables: ThemeVars;
}

const serif = `"Fraunces Variable", "Iowan Old Style", "Palatino Linotype", Palatino, "Book Antiqua", Georgia, serif`;
const sans = `-apple-system, "Segoe UI", Roboto, system-ui, sans-serif`;
const mono = `"Cascadia Code", "JetBrains Mono", "IBM Plex Mono", ui-monospace, Consolas, monospace`;
const geometric = `"Aptos Display", "Segoe UI", Roboto, system-ui, sans-serif`;
const constructivist = `"Arial Narrow", "Aptos", "Segoe UI", system-ui, sans-serif`;
const pixel = `"Lucida Console", "Cascadia Code", "Courier New", monospace`;

const baseNavGlyphs: Record<ThemeNavKey, string> = {
  atlas: "◆",
  gates: "▤",
  library: "▦",
  flow: "⚗",
  run: "▷",
  compare: "⇄",
  search: "⌕",
};

export const DEFAULT_EXPLORER_THEME_ID: ExplorerThemeId = "sunset-vellum";
export const EXPLORER_THEME_STORAGE_KEY = "lofn-explorer-theme";

export const EXPLORER_THEMES: ExplorerTheme[] = [
  {
    id: "sunset-vellum",
    name: "Sunset Vellum",
    shortName: "Sunset",
    description: "The default: a working sky at dusk read as an instrument — warm near-white ground, sunset rail tints, and saturation hoarded so only a line-stopping gate is allowed to shout.",
    colorScheme: "light",
    swatches: ["#fdf6ef", "#e0a15c", "#c0392b", "#8e44ad", "#a87595"],
    brandGlyph: "◗",
    navGlyphs: baseNavGlyphs,
    typography: "Literary serif for the voice; tabular mono for the measurements.",
    iconography: "Horizon strata, a hypsometric severity key, gilt-framed canon.",
    variables: {
      "--bg": "#fdf6ef",
      "--surface": "#fbeee4",
      "--surface-2": "#f6e3d6",
      "--surface-3": "#efd8c6",
      "--border": "#e7ccb9",
      "--border-strong": "#d6b19a",
      "--text": "#3a2a28",
      "--text-dim": "#7a6a63",
      "--text-faint": "#a8988f",
      "--accent": "#c85a3c",
      "--accent-2": "#e89a6a",
      "--accent-dim": "#a8482e",
      "--gold": "#c99a3c",
      "--gold-ink": "#2c1e16",
      "--ok": "#3e8e6e",
      "--dirty": "#c4791c",
      "--sev-hard": "#c0392b",
      "--sev-flag": "#c97b10",
      "--sev-prose": "#9a8478",
      "--sev-mixed": "#8e44ad",
      "--rail-orchestrator": "#a87595",
      "--rail-music": "#c56a72",
      "--rail-image": "#bc8a54",
      "--rail-video": "#a5924e",
      "--rail-story": "#8e77ae",
      "--canon-fill": "#fff9ec",
      "--canon-edge": "#d8b15a",
      "--display": serif,
      "--sans": sans,
      "--mono": mono,
      "--r": "4px",
      "--r-sm": "3px",
      "--shadow": "0 12px 30px rgba(120, 70, 40, 0.14)",
      "--thread": "#d8b15a",
      "--bg-glow": "rgba(232, 150, 90, 0.12)",
      "--theme-icon-bg": "rgba(200, 90, 60, 0.10)",
      "--theme-icon-fg": "#a8482e",
      "--theme-icon-border": "rgba(200, 90, 60, 0.30)",
      "--theme-icon-shadow": "0 6px 16px rgba(200, 90, 60, 0.12)",
      "--theme-preview-fallback": "linear-gradient(135deg, #fdf6ef, #e0a15c 45%, #c98ba6)",
    },
  },
  {
    id: "gilded-vellum",
    name: "Gilded Vellum",
    shortName: "Vellum",
    description: "The original long-session canon theme: dark vellum, gold semantic reserve, manuscript typography.",
    colorScheme: "dark",
    swatches: ["#13110c", "#ece3d1", "#c9a227", "#db463c", "#4fb1a3"],
    brandGlyph: "✦",
    navGlyphs: baseNavGlyphs,
    typography: "Literary serif display with operator mono.",
    iconography: "Manuscript marks, gates, and gilt thread symbols.",
    variables: {
      "--bg": "#13110c",
      "--surface": "#1b1712",
      "--surface-2": "#241f16",
      "--surface-3": "#2f2818",
      "--border": "#38301f",
      "--border-strong": "#4f4330",
      "--text": "#ece3d1",
      "--text-dim": "#a89e88",
      "--text-faint": "#7a6f59",
      "--accent": "#c9a227",
      "--accent-2": "#eccb6d",
      "--accent-dim": "#9a801e",
      "--gold": "#c9a227",
      "--gold-ink": "#1a1305",
      "--ok": "#5fae86",
      "--dirty": "#cf9440",
      "--sev-hard": "#db463c",
      "--sev-flag": "#dd922f",
      "--sev-prose": "#948a73",
      "--sev-mixed": "#b06ba2",
      "--rail-orchestrator": "#6f93d4",
      "--rail-music": "#d76c88",
      "--rail-image": "#4fb1a3",
      "--rail-video": "#cf8048",
      "--rail-story": "#86bb5f",
      "--display": serif,
      "--sans": sans,
      "--mono": mono,
      "--r": "3px",
      "--r-sm": "2px",
      "--shadow": "0 10px 34px rgba(0, 0, 0, 0.5)",
      "--thread": "#c9a227",
      "--bg-glow": "rgba(201, 162, 39, 0.05)",
      "--theme-icon-bg": "rgba(201, 162, 39, 0.10)",
      "--theme-icon-fg": "#eccb6d",
      "--theme-icon-border": "rgba(201, 162, 39, 0.32)",
      "--theme-icon-shadow": "0 0 8px rgba(201, 162, 39, 0.20)",
      "--theme-preview-fallback": "linear-gradient(135deg, #1b1712, #2f2818 55%, #c9a227)",
    },
  },
  {
    id: "sunset-synthwave",
    name: "Sunset Synthwave",
    shortName: "Synthwave",
    description: "Chrome rails, magenta/cyan gates, and a hard sunset horizon for high-voltage flow work.",
    art: "/theme-art/sunset-synthwave.png",
    colorScheme: "dark",
    swatches: ["#10091a", "#ff6ab7", "#33f5ff", "#ff9f43", "#26133b"],
    brandGlyph: "◩",
    navGlyphs: { atlas: "▰", gates: "◬", library: "≋", flow: "⌁", run: "▷", compare: "⇆", search: "⌕" },
    typography: "Retrowave geometric display with bright mono readouts.",
    iconography: "Chrome triangles, waveforms, horizon panels.",
    variables: {
      "--bg": "#10091a",
      "--surface": "#181026",
      "--surface-2": "#211334",
      "--surface-3": "#2b1744",
      "--border": "#4b2d61",
      "--border-strong": "#76438d",
      "--text": "#ffe7f7",
      "--text-dim": "#d7a8d2",
      "--text-faint": "#8e6b9b",
      "--accent": "#ff6ab7",
      "--accent-2": "#33f5ff",
      "--accent-dim": "#c83c92",
      "--gold": "#ff9f43",
      "--gold-ink": "#180818",
      "--ok": "#43e8b4",
      "--dirty": "#ffb84f",
      "--sev-hard": "#ff466b",
      "--sev-flag": "#ff9f43",
      "--sev-prose": "#9d89c7",
      "--sev-mixed": "#33f5ff",
      "--rail-orchestrator": "#ff9f43",
      "--rail-music": "#ff4fd8",
      "--rail-image": "#33f5ff",
      "--rail-video": "#8c7bff",
      "--rail-story": "#ffd166",
      "--display": geometric,
      "--sans": sans,
      "--mono": mono,
      "--r": "4px",
      "--r-sm": "3px",
      "--shadow": "0 18px 42px rgba(255, 74, 196, 0.15), 0 10px 34px rgba(0, 0, 0, 0.56)",
      "--thread": "#33f5ff",
      "--bg-glow": "rgba(255, 106, 183, 0.10)",
      "--theme-icon-bg": "rgba(51, 245, 255, 0.10)",
      "--theme-icon-fg": "#33f5ff",
      "--theme-icon-border": "rgba(255, 106, 183, 0.45)",
      "--theme-icon-shadow": "0 0 12px rgba(51, 245, 255, 0.35)",
      "--theme-preview-fallback": "linear-gradient(135deg, #10091a, #ff6ab7 52%, #33f5ff)",
    },
  },
  {
    id: "pixel-arcade",
    name: "8-bit",
    shortName: "8-bit",
    description: "Sharp pixel grids, phosphor status lights, and cartridge-era operator feedback.",
    art: "/theme-art/pixel-arcade.png",
    colorScheme: "dark",
    swatches: ["#09111f", "#76ff7a", "#ffd24d", "#ff5c5c", "#36a3ff"],
    brandGlyph: "▣",
    navGlyphs: { atlas: "▦", gates: "▣", library: "▤", flow: "▧", run: "▶", compare: "▥", search: "⌗" },
    typography: "Monospace-first, square, compact.",
    iconography: "Block glyphs, cartridge grids, status pixels.",
    variables: {
      "--bg": "#09111f",
      "--surface": "#0e1729",
      "--surface-2": "#121d33",
      "--surface-3": "#182642",
      "--border": "#2d4264",
      "--border-strong": "#4e6a94",
      "--text": "#e8ffd6",
      "--text-dim": "#a9d6a6",
      "--text-faint": "#6f8a86",
      "--accent": "#76ff7a",
      "--accent-2": "#ffd24d",
      "--accent-dim": "#45bd53",
      "--gold": "#ffd24d",
      "--gold-ink": "#07110a",
      "--ok": "#76ff7a",
      "--dirty": "#ffd24d",
      "--sev-hard": "#ff5c5c",
      "--sev-flag": "#ffb84d",
      "--sev-prose": "#7d93ad",
      "--sev-mixed": "#36a3ff",
      "--rail-orchestrator": "#36a3ff",
      "--rail-music": "#ff5cc8",
      "--rail-image": "#76ff7a",
      "--rail-video": "#ffd24d",
      "--rail-story": "#b58cff",
      "--display": pixel,
      "--sans": pixel,
      "--mono": pixel,
      "--r": "0px",
      "--r-sm": "0px",
      "--shadow": "0 0 0 1px rgba(118, 255, 122, 0.08), 0 12px 0 rgba(0, 0, 0, 0.25)",
      "--thread": "#76ff7a",
      "--bg-glow": "rgba(118, 255, 122, 0.06)",
      "--theme-icon-bg": "rgba(118, 255, 122, 0.10)",
      "--theme-icon-fg": "#76ff7a",
      "--theme-icon-border": "rgba(118, 255, 122, 0.50)",
      "--theme-icon-shadow": "0 0 0 1px rgba(118, 255, 122, 0.20)",
      "--theme-preview-fallback": "linear-gradient(135deg, #09111f, #182642 58%, #76ff7a)",
    },
  },
  {
    id: "pastel-butterfly",
    name: "Pastel Butterfly",
    shortName: "Butterfly",
    description: "Soft scientific-pastel surfaces, wing-vein rails, and gentle precision for browsing libraries.",
    art: "/theme-art/pastel-butterfly.png",
    colorScheme: "light",
    swatches: ["#f8f1fa", "#8f7bdc", "#8bd8c5", "#f29fbc", "#2b2637"],
    brandGlyph: "⋈",
    navGlyphs: { atlas: "◇", gates: "◈", library: "☷", flow: "∞", run: "▷", compare: "⋈", search: "⌕" },
    typography: "Airy serif display with soft system UI.",
    iconography: "Wing geometry, specimen pins, translucent diamonds.",
    variables: {
      "--bg": "#f8f1fa",
      "--surface": "#fffafe",
      "--surface-2": "#f1e9f7",
      "--surface-3": "#e7dff2",
      "--border": "#dccde8",
      "--border-strong": "#bba7d0",
      "--text": "#2b2637",
      "--text-dim": "#625b73",
      "--text-faint": "#8b8398",
      "--accent": "#8f7bdc",
      "--accent-2": "#f29fbc",
      "--accent-dim": "#7462c4",
      "--gold": "#d9a64d",
      "--gold-ink": "#251e33",
      "--ok": "#3e9f85",
      "--dirty": "#d8913b",
      "--sev-hard": "#c84d67",
      "--sev-flag": "#d8913b",
      "--sev-prose": "#8b8398",
      "--sev-mixed": "#9a6bcc",
      "--rail-orchestrator": "#8f7bdc",
      "--rail-music": "#f29fbc",
      "--rail-image": "#58bda9",
      "--rail-video": "#8ab5e6",
      "--rail-story": "#c9b457",
      "--display": serif,
      "--sans": `"Aptos", "Segoe UI", Roboto, system-ui, sans-serif`,
      "--mono": mono,
      "--r": "6px",
      "--r-sm": "5px",
      "--shadow": "0 12px 30px rgba(101, 79, 128, 0.16)",
      "--thread": "#8f7bdc",
      "--bg-glow": "rgba(242, 159, 188, 0.16)",
      "--theme-icon-bg": "rgba(143, 123, 220, 0.12)",
      "--theme-icon-fg": "#7462c4",
      "--theme-icon-border": "rgba(143, 123, 220, 0.28)",
      "--theme-icon-shadow": "0 6px 18px rgba(143, 123, 220, 0.16)",
      "--theme-preview-fallback": "linear-gradient(135deg, #f8f1fa, #8bd8c5 45%, #f29fbc)",
    },
  },
  {
    id: "art-nouveau-fairies",
    name: "Art Nouveau Fairies",
    shortName: "Nouveau",
    description: "Peacock glass, vine-like rails, jewel gates, and fairy-ornament iconography.",
    art: "/theme-art/art-nouveau-fairies.png",
    colorScheme: "dark",
    swatches: ["#101716", "#1f6f65", "#d8b965", "#7f4f8f", "#e9dfc6"],
    brandGlyph: "✿",
    navGlyphs: { atlas: "◜", gates: "✧", library: "☰", flow: "♒", run: "❯", compare: "☍", search: "⌕" },
    typography: "Ornamental serif display with restrained body text.",
    iconography: "Vines, jewels, arches, clasp-like gates.",
    variables: {
      "--bg": "#101716",
      "--surface": "#15211f",
      "--surface-2": "#1b2b28",
      "--surface-3": "#233936",
      "--border": "#38524c",
      "--border-strong": "#5c756a",
      "--text": "#e9dfc6",
      "--text-dim": "#b9ad92",
      "--text-faint": "#837a68",
      "--accent": "#d8b965",
      "--accent-2": "#7ce0c4",
      "--accent-dim": "#9f8642",
      "--gold": "#d8b965",
      "--gold-ink": "#111812",
      "--ok": "#65c49a",
      "--dirty": "#c98855",
      "--sev-hard": "#d65a6f",
      "--sev-flag": "#d19a49",
      "--sev-prose": "#958e7c",
      "--sev-mixed": "#b678bd",
      "--rail-orchestrator": "#7ce0c4",
      "--rail-music": "#d76d9a",
      "--rail-image": "#79b56a",
      "--rail-video": "#d8b965",
      "--rail-story": "#7f4f8f",
      "--display": serif,
      "--sans": sans,
      "--mono": mono,
      "--r": "5px",
      "--r-sm": "4px",
      "--shadow": "0 18px 38px rgba(0, 0, 0, 0.42)",
      "--thread": "#d8b965",
      "--bg-glow": "rgba(124, 224, 196, 0.07)",
      "--theme-icon-bg": "rgba(216, 185, 101, 0.10)",
      "--theme-icon-fg": "#d8b965",
      "--theme-icon-border": "rgba(124, 224, 196, 0.28)",
      "--theme-icon-shadow": "0 0 10px rgba(124, 224, 196, 0.18)",
      "--theme-preview-fallback": "linear-gradient(135deg, #101716, #1f6f65 50%, #d8b965)",
    },
  },
  {
    id: "lunar-ink-observatory",
    name: "Lunar Ink Observatory",
    shortName: "Lunar Ink",
    description: "Sumi ink, moon silver, and star-map iconography for quiet deep work.",
    art: "/theme-art/lunar-ink-observatory.png",
    colorScheme: "dark",
    swatches: ["#080b12", "#d9e2ea", "#3d5f9e", "#b79d68", "#111a2c"],
    brandGlyph: "☾",
    navGlyphs: { atlas: "✦", gates: "◐", library: "☰", flow: "⌁", run: "▷", compare: "☍", search: "⌕" },
    typography: "Quiet serif headings with observatory mono.",
    iconography: "Moons, constellations, lenses, star pins.",
    variables: {
      "--bg": "#080b12",
      "--surface": "#0d121c",
      "--surface-2": "#111a2c",
      "--surface-3": "#17233a",
      "--border": "#293650",
      "--border-strong": "#485a7a",
      "--text": "#e6edf3",
      "--text-dim": "#a6b3c5",
      "--text-faint": "#69768d",
      "--accent": "#d9e2ea",
      "--accent-2": "#6e9cff",
      "--accent-dim": "#9aa7b8",
      "--gold": "#b79d68",
      "--gold-ink": "#0a0d13",
      "--ok": "#74c6a1",
      "--dirty": "#b79d68",
      "--sev-hard": "#d85d6b",
      "--sev-flag": "#c99857",
      "--sev-prose": "#7d8799",
      "--sev-mixed": "#8b79d8",
      "--rail-orchestrator": "#8da9e8",
      "--rail-music": "#a787d9",
      "--rail-image": "#74c6a1",
      "--rail-video": "#b79d68",
      "--rail-story": "#7fb6d6",
      "--display": serif,
      "--sans": sans,
      "--mono": mono,
      "--r": "4px",
      "--r-sm": "3px",
      "--shadow": "0 14px 36px rgba(0, 0, 0, 0.58)",
      "--thread": "#d9e2ea",
      "--bg-glow": "rgba(110, 156, 255, 0.07)",
      "--theme-icon-bg": "rgba(217, 226, 234, 0.08)",
      "--theme-icon-fg": "#d9e2ea",
      "--theme-icon-border": "rgba(110, 156, 255, 0.30)",
      "--theme-icon-shadow": "0 0 10px rgba(110, 156, 255, 0.16)",
      "--theme-preview-fallback": "linear-gradient(135deg, #080b12, #17233a 60%, #d9e2ea)",
    },
  },
  {
    id: "solarpunk-glasshouse",
    name: "Solarpunk Glasshouse",
    shortName: "Glasshouse",
    description: "Greenhouse glass, copper trellises, and living-circuit rails for optimistic operations.",
    art: "/theme-art/solarpunk-glasshouse.png",
    colorScheme: "light",
    swatches: ["#f4f6e8", "#3f9b64", "#e0a936", "#51b7c7", "#22322a"],
    brandGlyph: "☼",
    navGlyphs: { atlas: "⌬", gates: "◉", library: "▤", flow: "∿", run: "▷", compare: "⇄", search: "⌕" },
    typography: "Warm readable system type with botanical serif headings.",
    iconography: "Sun cells, leaf veins, trellises, seed-pod gates.",
    variables: {
      "--bg": "#f4f6e8",
      "--surface": "#fffdf0",
      "--surface-2": "#e9f0dc",
      "--surface-3": "#dce8ce",
      "--border": "#c6d0b7",
      "--border-strong": "#96aa86",
      "--text": "#22322a",
      "--text-dim": "#536252",
      "--text-faint": "#788773",
      "--accent": "#3f9b64",
      "--accent-2": "#e0a936",
      "--accent-dim": "#2f7c50",
      "--gold": "#c78628",
      "--gold-ink": "#132015",
      "--ok": "#3f9b64",
      "--dirty": "#c78628",
      "--sev-hard": "#bd4f4f",
      "--sev-flag": "#c78628",
      "--sev-prose": "#7b856f",
      "--sev-mixed": "#8a6bb8",
      "--rail-orchestrator": "#51b7c7",
      "--rail-music": "#d76e82",
      "--rail-image": "#3f9b64",
      "--rail-video": "#c78628",
      "--rail-story": "#7caa3d",
      "--display": serif,
      "--sans": sans,
      "--mono": mono,
      "--r": "6px",
      "--r-sm": "5px",
      "--shadow": "0 14px 32px rgba(64, 98, 72, 0.18)",
      "--thread": "#3f9b64",
      "--bg-glow": "rgba(224, 169, 54, 0.13)",
      "--theme-icon-bg": "rgba(63, 155, 100, 0.12)",
      "--theme-icon-fg": "#2f7c50",
      "--theme-icon-border": "rgba(63, 155, 100, 0.28)",
      "--theme-icon-shadow": "0 8px 22px rgba(63, 155, 100, 0.14)",
      "--theme-preview-fallback": "linear-gradient(135deg, #f4f6e8, #51b7c7 45%, #3f9b64)",
    },
  },
  {
    id: "bioluminescent-tidepool",
    name: "Bioluminescent Tidepool",
    shortName: "Tidepool",
    description: "Abyssal navy, plankton rails, and coral status chips for luminous night work.",
    art: "/theme-art/bioluminescent-tidepool.png",
    colorScheme: "dark",
    swatches: ["#06121b", "#42f2d2", "#ff6f61", "#a7e4bf", "#26323f"],
    brandGlyph: "◌",
    navGlyphs: { atlas: "⊙", gates: "◍", library: "▤", flow: "∿", run: "▷", compare: "◑", search: "⌕" },
    typography: "Clear sans with liquid mono accents.",
    iconography: "Anemone dots, tide marks, shell drawers, current lines.",
    variables: {
      "--bg": "#06121b",
      "--surface": "#0a1a25",
      "--surface-2": "#102433",
      "--surface-3": "#163244",
      "--border": "#26485a",
      "--border-strong": "#3b7180",
      "--text": "#dff9f5",
      "--text-dim": "#99c9c4",
      "--text-faint": "#62868d",
      "--accent": "#42f2d2",
      "--accent-2": "#ff6f61",
      "--accent-dim": "#2bb8a4",
      "--gold": "#a7e4bf",
      "--gold-ink": "#06121b",
      "--ok": "#75d99b",
      "--dirty": "#d99a4d",
      "--sev-hard": "#ff6f61",
      "--sev-flag": "#d99a4d",
      "--sev-prose": "#78929a",
      "--sev-mixed": "#9d7ee6",
      "--rail-orchestrator": "#6da8ff",
      "--rail-music": "#ff6f9c",
      "--rail-image": "#42f2d2",
      "--rail-video": "#d99a4d",
      "--rail-story": "#75d99b",
      "--display": geometric,
      "--sans": sans,
      "--mono": mono,
      "--r": "5px",
      "--r-sm": "4px",
      "--shadow": "0 16px 42px rgba(0, 0, 0, 0.55), 0 0 24px rgba(66, 242, 210, 0.08)",
      "--thread": "#42f2d2",
      "--bg-glow": "rgba(66, 242, 210, 0.08)",
      "--theme-icon-bg": "rgba(66, 242, 210, 0.10)",
      "--theme-icon-fg": "#42f2d2",
      "--theme-icon-border": "rgba(66, 242, 210, 0.34)",
      "--theme-icon-shadow": "0 0 12px rgba(66, 242, 210, 0.25)",
      "--theme-preview-fallback": "linear-gradient(135deg, #06121b, #163244 58%, #42f2d2)",
    },
  },
  {
    id: "gothic-botanical-lab",
    name: "Gothic Botanical Lab",
    shortName: "Botanical Lab",
    description: "Engraved black glass, oxblood gates, and herbarium structure for severe QA work.",
    art: "/theme-art/gothic-botanical-lab.png",
    colorScheme: "dark",
    swatches: ["#120f13", "#e4dccb", "#a83246", "#78a65a", "#3a3039"],
    brandGlyph: "✥",
    navGlyphs: { atlas: "✣", gates: "◆", library: "▥", flow: "⌬", run: "▷", compare: "☍", search: "⌕" },
    typography: "Grave serif headings with surgical mono.",
    iconography: "Wax seals, thorns, specimen plates, black-glass maps.",
    variables: {
      "--bg": "#120f13",
      "--surface": "#1a151a",
      "--surface-2": "#241d23",
      "--surface-3": "#312731",
      "--border": "#453843",
      "--border-strong": "#69545f",
      "--text": "#e4dccb",
      "--text-dim": "#b5a99a",
      "--text-faint": "#7c7074",
      "--accent": "#a83246",
      "--accent-2": "#d6b56f",
      "--accent-dim": "#81283a",
      "--gold": "#d6b56f",
      "--gold-ink": "#140f12",
      "--ok": "#78a65a",
      "--dirty": "#bd874d",
      "--sev-hard": "#d64a5f",
      "--sev-flag": "#bd874d",
      "--sev-prose": "#8d8184",
      "--sev-mixed": "#8c6db2",
      "--rail-orchestrator": "#7897c2",
      "--rail-music": "#a83246",
      "--rail-image": "#78a65a",
      "--rail-video": "#bd874d",
      "--rail-story": "#b08bb8",
      "--display": serif,
      "--sans": sans,
      "--mono": mono,
      "--r": "3px",
      "--r-sm": "2px",
      "--shadow": "0 18px 44px rgba(0, 0, 0, 0.60)",
      "--thread": "#a83246",
      "--bg-glow": "rgba(168, 50, 70, 0.08)",
      "--theme-icon-bg": "rgba(168, 50, 70, 0.12)",
      "--theme-icon-fg": "#d6b56f",
      "--theme-icon-border": "rgba(168, 50, 70, 0.38)",
      "--theme-icon-shadow": "0 0 10px rgba(168, 50, 70, 0.28)",
      "--theme-preview-fallback": "linear-gradient(135deg, #120f13, #312731 58%, #a83246)",
    },
  },
  {
    id: "bauhaus-signal-room",
    name: "Bauhaus Signal Room",
    shortName: "Bauhaus",
    description: "Modernist geometry, signal colors, and mechanical indicators for strict flow editing.",
    art: "/theme-art/bauhaus-signal-room.png",
    colorScheme: "light",
    swatches: ["#f4efe2", "#d7352a", "#1f62b2", "#e7b500", "#101010"],
    brandGlyph: "●",
    navGlyphs: { atlas: "■", gates: "●", library: "▭", flow: "▲", run: "▶", compare: "◆", search: "⌕" },
    typography: "Constructivist condensed labels with plain body text.",
    iconography: "Circles, squares, triangles, ruled signal marks.",
    variables: {
      "--bg": "#f4efe2",
      "--surface": "#fff9ea",
      "--surface-2": "#eee5d2",
      "--surface-3": "#ded2ba",
      "--border": "#c8bda8",
      "--border-strong": "#988b73",
      "--text": "#101010",
      "--text-dim": "#4e493f",
      "--text-faint": "#7a7163",
      "--accent": "#d7352a",
      "--accent-2": "#1f62b2",
      "--accent-dim": "#a82721",
      "--gold": "#e7b500",
      "--gold-ink": "#101010",
      "--ok": "#2d8a62",
      "--dirty": "#b97920",
      "--sev-hard": "#d7352a",
      "--sev-flag": "#b97920",
      "--sev-prose": "#7a7163",
      "--sev-mixed": "#1f62b2",
      "--rail-orchestrator": "#1f62b2",
      "--rail-music": "#d7352a",
      "--rail-image": "#2d8a62",
      "--rail-video": "#b97920",
      "--rail-story": "#6a56aa",
      "--display": constructivist,
      "--sans": sans,
      "--mono": mono,
      "--r": "1px",
      "--r-sm": "1px",
      "--shadow": "8px 8px 0 rgba(16, 16, 16, 0.10)",
      "--thread": "#d7352a",
      "--bg-glow": "rgba(215, 53, 42, 0.08)",
      "--theme-icon-bg": "rgba(215, 53, 42, 0.10)",
      "--theme-icon-fg": "#101010",
      "--theme-icon-border": "rgba(16, 16, 16, 0.45)",
      "--theme-icon-shadow": "3px 3px 0 rgba(16, 16, 16, 0.12)",
      "--theme-preview-fallback": "linear-gradient(135deg, #f4efe2, #e7b500 42%, #d7352a)",
    },
  },
  {
    id: "desert-chrome-mirage",
    name: "Desert Chrome Mirage",
    shortName: "Mirage",
    description: "Sandblasted stone, chrome reflections, and route-marker gates for field navigation energy.",
    art: "/theme-art/desert-chrome-mirage.png",
    colorScheme: "light",
    swatches: ["#efe3d1", "#c96145", "#3a8d98", "#e6b35f", "#211816"],
    brandGlyph: "◒",
    navGlyphs: { atlas: "⌖", gates: "◇", library: "▤", flow: "⌁", run: "▷", compare: "◫", search: "⌕" },
    typography: "Industrial sans labels with warm field-note body text.",
    iconography: "Cairns, horizons, route marks, mirrored plates.",
    variables: {
      "--bg": "#efe3d1",
      "--surface": "#fbf1df",
      "--surface-2": "#e6d5bd",
      "--surface-3": "#d4c0a6",
      "--border": "#bda487",
      "--border-strong": "#8f765f",
      "--text": "#211816",
      "--text-dim": "#5e5049",
      "--text-faint": "#88786c",
      "--accent": "#c96145",
      "--accent-2": "#3a8d98",
      "--accent-dim": "#9e4b35",
      "--gold": "#e6b35f",
      "--gold-ink": "#211816",
      "--ok": "#4d8d69",
      "--dirty": "#c98737",
      "--sev-hard": "#c96145",
      "--sev-flag": "#c98737",
      "--sev-prose": "#88786c",
      "--sev-mixed": "#6d6aae",
      "--rail-orchestrator": "#3a8d98",
      "--rail-music": "#c96145",
      "--rail-image": "#4d8d69",
      "--rail-video": "#c98737",
      "--rail-story": "#7f6bb0",
      "--display": geometric,
      "--sans": sans,
      "--mono": mono,
      "--r": "4px",
      "--r-sm": "3px",
      "--shadow": "0 16px 36px rgba(85, 62, 45, 0.20)",
      "--thread": "#3a8d98",
      "--bg-glow": "rgba(230, 179, 95, 0.16)",
      "--theme-icon-bg": "rgba(58, 141, 152, 0.12)",
      "--theme-icon-fg": "#3a8d98",
      "--theme-icon-border": "rgba(201, 97, 69, 0.30)",
      "--theme-icon-shadow": "0 8px 18px rgba(85, 62, 45, 0.15)",
      "--theme-preview-fallback": "linear-gradient(135deg, #efe3d1, #c96145 52%, #3a8d98)",
    },
  },
  {
    id: "paper-lantern-rain",
    name: "Paper Lantern Rain",
    shortName: "Lantern Rain",
    description: "Washi, lacquer, vermilion thread, and rain-glass contrast for contemplative editing.",
    art: "/theme-art/paper-lantern-rain.png",
    colorScheme: "dark",
    swatches: ["#0f1012", "#d94b35", "#e1a94d", "#6b91a8", "#e7dcc4"],
    brandGlyph: "◍",
    navGlyphs: { atlas: "◇", gates: "◈", library: "▤", flow: "〰", run: "▷", compare: "◫", search: "⌕" },
    typography: "Quiet paper-serif headings with restrained system body.",
    iconography: "Thread paths, paper folds, lantern seals, rain circles.",
    variables: {
      "--bg": "#0f1012",
      "--surface": "#171719",
      "--surface-2": "#202024",
      "--surface-3": "#2a2a30",
      "--border": "#3d3c42",
      "--border-strong": "#5e5960",
      "--text": "#e7dcc4",
      "--text-dim": "#b4a994",
      "--text-faint": "#7b7469",
      "--accent": "#d94b35",
      "--accent-2": "#e1a94d",
      "--accent-dim": "#a83729",
      "--gold": "#e1a94d",
      "--gold-ink": "#120e0d",
      "--ok": "#7aa985",
      "--dirty": "#c7883f",
      "--sev-hard": "#d94b35",
      "--sev-flag": "#c7883f",
      "--sev-prose": "#81786f",
      "--sev-mixed": "#8b75bd",
      "--rail-orchestrator": "#6b91a8",
      "--rail-music": "#d94b35",
      "--rail-image": "#7aa985",
      "--rail-video": "#c7883f",
      "--rail-story": "#b69a63",
      "--display": serif,
      "--sans": sans,
      "--mono": mono,
      "--r": "4px",
      "--r-sm": "3px",
      "--shadow": "0 18px 42px rgba(0, 0, 0, 0.58)",
      "--thread": "#d94b35",
      "--bg-glow": "rgba(217, 75, 53, 0.08)",
      "--theme-icon-bg": "rgba(217, 75, 53, 0.12)",
      "--theme-icon-fg": "#e1a94d",
      "--theme-icon-border": "rgba(225, 169, 77, 0.28)",
      "--theme-icon-shadow": "0 0 10px rgba(225, 169, 77, 0.18)",
      "--theme-preview-fallback": "linear-gradient(135deg, #0f1012, #d94b35 52%, #6b91a8)",
    },
  },
  {
    id: "arctic-aurora-codex",
    name: "Arctic Aurora Codex",
    shortName: "Aurora",
    description: "Polar night contrast, aurora rails, and ice-crystal gates for cold-precision work.",
    art: "/theme-art/arctic-aurora-codex.png",
    colorScheme: "dark",
    swatches: ["#07121f", "#6ff2a2", "#9a7cff", "#bfe7ff", "#253447"],
    brandGlyph: "⌁",
    navGlyphs: { atlas: "⌬", gates: "◇", library: "▤", flow: "∿", run: "▷", compare: "◫", search: "⌕" },
    typography: "Crisp sans with expedition-log mono.",
    iconography: "Field lines, prisms, beacons, frost marks.",
    variables: {
      "--bg": "#07121f",
      "--surface": "#0d1a2b",
      "--surface-2": "#142338",
      "--surface-3": "#1c304b",
      "--border": "#2c4664",
      "--border-strong": "#496b8f",
      "--text": "#e4f7ff",
      "--text-dim": "#a8c9d9",
      "--text-faint": "#6f8b9f",
      "--accent": "#6ff2a2",
      "--accent-2": "#9a7cff",
      "--accent-dim": "#4dbf85",
      "--gold": "#bfe7ff",
      "--gold-ink": "#07121f",
      "--ok": "#6ff2a2",
      "--dirty": "#c49a54",
      "--sev-hard": "#ee6a78",
      "--sev-flag": "#c49a54",
      "--sev-prose": "#8195a8",
      "--sev-mixed": "#9a7cff",
      "--rail-orchestrator": "#8cb8ff",
      "--rail-music": "#e875b1",
      "--rail-image": "#6ff2a2",
      "--rail-video": "#bfe7ff",
      "--rail-story": "#9a7cff",
      "--display": geometric,
      "--sans": sans,
      "--mono": mono,
      "--r": "4px",
      "--r-sm": "3px",
      "--shadow": "0 18px 44px rgba(0, 0, 0, 0.58), 0 0 24px rgba(111, 242, 162, 0.08)",
      "--thread": "#6ff2a2",
      "--bg-glow": "rgba(154, 124, 255, 0.09)",
      "--theme-icon-bg": "rgba(111, 242, 162, 0.10)",
      "--theme-icon-fg": "#6ff2a2",
      "--theme-icon-border": "rgba(154, 124, 255, 0.35)",
      "--theme-icon-shadow": "0 0 12px rgba(111, 242, 162, 0.22)",
      "--theme-preview-fallback": "linear-gradient(135deg, #07121f, #1c304b 58%, #6ff2a2)",
    },
  },
];

const themeById = Object.fromEntries(EXPLORER_THEMES.map((theme) => [theme.id, theme])) as Record<ExplorerThemeId, ExplorerTheme>;

export const EXPLORER_THEME_VARIABLE_KEYS = Array.from(
  new Set(EXPLORER_THEMES.flatMap((theme) => Object.keys(theme.variables))),
);

export function getExplorerTheme(id: string | null | undefined): ExplorerTheme {
  return themeById[(id || DEFAULT_EXPLORER_THEME_ID) as ExplorerThemeId] || themeById[DEFAULT_EXPLORER_THEME_ID];
}

export function applyExplorerTheme(theme: ExplorerTheme) {
  const root = document.documentElement;
  root.dataset.theme = theme.id;
  root.style.colorScheme = theme.colorScheme;
  EXPLORER_THEME_VARIABLE_KEYS.forEach((key) => root.style.removeProperty(key));
  Object.entries(theme.variables).forEach(([key, value]) => root.style.setProperty(key, value));
}
